# Generated by Django 4.1.5 on 2023-01-15 03:58

from django.db import migrations, models
import django.db.models.deletion
import registry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=20, validators=[registry.models.validate_ci])),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[registry.models.validate_age])),
                ('sex', models.CharField(choices=[('M', 'Maculino'), ('F', 'Femenino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateTechs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.candidate')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.technology')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='techs',
            field=models.ManyToManyField(related_name='techs', through='registry.CandidateTechs', to='registry.technology'),
        ),
    ]
