# Generated by Django 4.1.5 on 2023-01-15 04:04

from django.db import migrations, models
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20230114_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='ci',
            field=models.CharField(max_length=20, unique=True, validators=[registry.models.validate_ci]),
        ),
    ]
